require('dotenv').config();

const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { Pool } = require('pg');

const port = Number(process.env.PORT || 3000);
const root = __dirname;
if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL não foi configurada no arquivo .env.');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});
const sessions = new Map();

async function initializeDatabase() {
  await pool.query(`
    create table if not exists accounts (
      id bigint generated by default as identity primary key,
      name text not null,
      email text not null unique,
      password_hash text not null,
      email_verified boolean not null default false,
      created_at timestamptz not null default now()
    );
    create table if not exists users (
      id bigint generated by default as identity primary key,
      name text not null,
      email text not null,
      phone text not null,
      status text not null default 'ativo',
      created_at timestamptz not null default now()
    );
    create table if not exists cards (
      id bigint generated by default as identity primary key,
      identifier text not null unique,
      user_name text not null,
      type text not null,
      status text not null default 'ativo',
      created_at timestamptz not null default now()
    );
    create table if not exists doors (
      id bigint generated by default as identity primary key,
      name text not null,
      description text not null,
      status text not null default 'fechada',
      created_at timestamptz not null default now()
    );
    create table if not exists access_logs (
      id bigint generated by default as identity primary key,
      user_name text not null,
      card text not null,
      door text not null,
      type text not null,
      status text not null,
      created_at timestamptz not null default now()
    );
    create table if not exists audit_logs (
      id bigint generated by default as identity primary key,
      account_id bigint references accounts(id),
      action text not null,
      details text,
      created_at timestamptz not null default now()
    );
  `);
  await pool.query(`insert into doors (name, description) values
    ('Porta Principal', 'Entrada do edifício'),
    ('Academia', 'Acesso à área de exercícios'),
    ('Sala de Reunião', 'Sala 201 - 2º andar')
    on conflict do nothing`);
  await pool.query(`insert into users (name, email, phone, status) values
    ('Usuário 1', 'user1@email.com', '(DDD) XXXXX-XXXX', 'ativo'),
    ('Usuário 2', 'user2@email.com', '(DDD) XXXXX-XXXX', 'ativo'),
    ('Usuário 3', 'user3@email.com', '(DDD) XXXXX-XXXX', 'inativo')
    on conflict do nothing`);
  await pool.query(`insert into cards (identifier, user_name, type, created_at) values
    ('A1:B2:C3:D4', 'Usuário 1', 'RFID', '2026-08-01T00:00:00Z'),
    ('E5:F6:G7:H8', 'Usuário 2', 'NFC', '2026-08-02T00:00:00Z')
    on conflict (identifier) do nothing`);
  const accesses = await pool.query('select count(*)::int as total from access_logs');
  if (accesses.rows[0].total === 0) {
    await pool.query(`insert into access_logs (user_name, card, door, type, status, created_at) values
      ('Usuário 1', 'A1:B2:C3:D4', 'Porta Principal', 'Cofre', 'Permitido', '2026-08-04T14:32:15Z'),
      ('Usuário 2', 'E5:F6:G7:H8', 'Academia', 'Porta', 'Permitido', '2026-08-04T14:28:42Z'),
      ('Usuário 3', 'I9:J0:K1:L2', 'Porta Principal', 'Porta', 'Negado', '2026-08-04T14:25:10Z')`);
  }
}

function send(response, status, data, headers = {}) {
  response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', ...headers });
  response.end(JSON.stringify(data));
}

function readBody(request) {
  return new Promise((resolve, reject) => {
    let body = '';
    request.on('data', chunk => { body += chunk; });
    request.on('end', () => {
      try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error('JSON inválido')); }
    });
    request.on('error', reject);
  });
}

function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')) {
  return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}`;
}

function passwordMatches(password, stored) {
  const [salt, hash] = stored.split(':');
  const candidate = crypto.scryptSync(password, salt, 64);
  return crypto.timingSafeEqual(candidate, Buffer.from(hash, 'hex'));
}

function tokenFor(accountId) {
  const token = crypto.randomBytes(32).toString('hex');
  sessions.set(token, accountId);
  return token;
}

function sessionToken(request) {
  return (request.headers.cookie || '').split(';').map(item => item.trim()).find(item => item.startsWith('lockcard_session='))?.split('=')[1];
}

async function accountFrom(request) {
  const id = sessions.get(sessionToken(request));
  if (!id) return null;
  const result = await pool.query('select id, name, email from accounts where id = $1', [id]);
  return result.rows[0] || null;
}

async function requireAccount(request, response) {
  const account = await accountFrom(request);
  if (!account) send(response, 401, { error: 'Faça login para continuar.' });
  return account;
}

async function logAction(accountId, action, details = '') {
  await pool.query('insert into audit_logs (account_id, action, details) values ($1, $2, $3)', [accountId, action, details]);
}

async function handleApi(request, response, url) {
  try {
    if (request.method === 'POST' && url.pathname === '/api/auth/register') {
      const { name, email, password } = await readBody(request);
      if (!name || !email || !password || password.length < 6) return send(response, 400, { error: 'Informe nome, e-mail e senha com pelo menos 6 caracteres.' });
      const normalizedEmail = email.trim().toLowerCase();
      const existing = await pool.query('select id from accounts where email = $1', [normalizedEmail]);
      if (existing.rowCount) return send(response, 409, { error: 'Este e-mail já está cadastrado.' });
      const result = await pool.query('insert into accounts (name, email, password_hash) values ($1, $2, $3) returning id, name, email', [name.trim(), normalizedEmail, hashPassword(password)]);
      const account = result.rows[0];
      const token = tokenFor(account.id);
      return send(response, 201, account, { 'Set-Cookie': `lockcard_session=${token}; HttpOnly; SameSite=Lax; Path=/` });
    }
    if (request.method === 'POST' && url.pathname === '/api/auth/login') {
      const { email, password } = await readBody(request);
      const result = await pool.query('select * from accounts where email = $1', [email?.trim().toLowerCase()]);
      const account = result.rows[0];
      if (!account || !passwordMatches(password || '', account.password_hash)) return send(response, 401, { error: 'E-mail ou senha inválidos.' });
      const token = tokenFor(account.id);
      await logAction(account.id, 'login');
      return send(response, 200, { name: account.name, email: account.email }, { 'Set-Cookie': `lockcard_session=${token}; HttpOnly; SameSite=Lax; Path=/` });
    }
    if (request.method === 'POST' && url.pathname === '/api/auth/logout') {
      sessions.delete(sessionToken(request));
      return send(response, 200, { ok: true }, { 'Set-Cookie': 'lockcard_session=; Max-Age=0; HttpOnly; SameSite=Lax; Path=/' });
    }
    if (request.method === 'GET' && url.pathname === '/api/auth/me') return send(response, 200, { account: await accountFrom(request) });

    const account = await requireAccount(request, response);
    if (!account) return;
    const resourceMatch = url.pathname.match(/^\/api\/(users|cards|doors)\/(\d+)$/);
    if (resourceMatch && request.method === 'PUT') {
      const [, resource, id] = resourceMatch;
      const body = await readBody(request);
      const statements = {
        users: ['update users set name = $1, email = $2, phone = $3, status = $4 where id = $5', [body.name, body.email, body.phone, body.status, id]],
        cards: ['update cards set identifier = $1, user_name = $2, type = $3, status = $4 where id = $5', [body.identifier, body.userName, body.type, body.status, id]],
        doors: ['update doors set name = $1, description = $2, status = $3 where id = $4', [body.name, body.description, body.status || 'fechada', id]]
      };
      const [sql, values] = statements[resource];
      const result = await pool.query(sql, values);
      if (!result.rowCount) return send(response, 404, { error: 'Registro não encontrado.' });
      await logAction(account.id, `update_${resource}`, id);
      return send(response, 200, { ok: true });
    }
    if (resourceMatch && request.method === 'DELETE') {
      const [, resource, id] = resourceMatch;
      const result = await pool.query(`delete from ${resource} where id = $1`, [id]);
      if (!result.rowCount) return send(response, 404, { error: 'Registro não encontrado.' });
      await logAction(account.id, `delete_${resource}`, id);
      return send(response, 200, { ok: true });
    }
    if (request.method === 'GET' && url.pathname === '/api/users') return send(response, 200, (await pool.query('select * from users order by id desc')).rows);
    if (request.method === 'POST' && url.pathname === '/api/users') {
      const body = await readBody(request);
      const result = await pool.query('insert into users (name, email, phone, status) values ($1, $2, $3, $4) returning *', [body.name, body.email, body.phone, body.status || 'ativo']);
      await logAction(account.id, 'create_user', body.email);
      return send(response, 201, result.rows[0]);
    }
    if (request.method === 'GET' && url.pathname === '/api/cards') return send(response, 200, (await pool.query('select * from cards order by id desc')).rows);
    if (request.method === 'POST' && url.pathname === '/api/cards') {
      const body = await readBody(request);
      const result = await pool.query('insert into cards (identifier, user_name, type) values ($1, $2, $3) returning *', [body.identifier, body.userName, body.type]);
      await logAction(account.id, 'create_card', body.identifier);
      return send(response, 201, result.rows[0]);
    }
    if (request.method === 'GET' && url.pathname === '/api/doors') return send(response, 200, (await pool.query('select * from doors order by id')).rows);
    if (request.method === 'POST' && url.pathname === '/api/doors') {
      const body = await readBody(request);
      const result = await pool.query('insert into doors (name, description) values ($1, $2) returning *', [body.name, body.description]);
      await logAction(account.id, 'create_door', body.name);
      return send(response, 201, result.rows[0]);
    }
    if (request.method === 'POST' && url.pathname === '/api/accesses') {
      const body = await readBody(request);
      await pool.query('insert into access_logs (user_name, card, door, type, status) values ($1, $2, $3, $4, $5)', [body.userName, body.card, body.door, body.type || 'Porta', body.status || 'Permitido']);
      await logAction(account.id, 'create_access', body.door);
      return send(response, 201, { ok: true });
    }
    if (request.method === 'GET' && url.pathname === '/api/accesses') return send(response, 200, (await pool.query('select * from access_logs order by id desc')).rows);
    return send(response, 404, { error: 'Rota não encontrada.' });
  } catch (error) {
    const message = error.code === '23505' ? 'Este registro já existe.' : 'Não foi possível concluir a operação.';
    console.error(error.message);
    return send(response, 400, { error: message });
  }
}

function serveStatic(request, response, url) {
  const requested = url.pathname === '/' ? '/index.html' : url.pathname;
  const filePath = path.resolve(root, `.${requested}`);
  if (!filePath.startsWith(root) || !fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) return send(response, 404, { error: 'Arquivo não encontrado.' });
  const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' };
  response.writeHead(200, { 'Content-Type': types[path.extname(filePath)] || 'application/octet-stream' });
  fs.createReadStream(filePath).pipe(response);
}

initializeDatabase().then(() => {
  http.createServer(async (request, response) => {
    const url = new URL(request.url, `http://${request.headers.host}`);
    if (url.pathname.startsWith('/api/')) return handleApi(request, response, url);
    if (request.method === 'GET') return serveStatic(request, response, url);
    send(response, 405, { error: 'Método não permitido.' });
  }).listen(port, () => console.log(`LockCard disponível em http://localhost:${port}`));
}).catch(error => {
  console.error('Não foi possível conectar ao Supabase:', error.message);
  process.exit(1);
});
